//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imposto.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaFiscal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotaFiscal()
        {
            this.NotaFiscalItem = new HashSet<NotaFiscalItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NumeroNotaFiscal { get; set; }
        public Nullable<int> Serie { get; set; }
        public string NomeCliente { get; set; }
        public string EstadoDestino { get; set; }
        public string EstadoOrigem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaFiscalItem> NotaFiscalItem { get; set; }
    }
}
