//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imposto.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaFiscalItem
    {
        public int Id { get; set; }
        public Nullable<int> IdNotaFiscal { get; set; }
        public string Cfop { get; set; }
        public string TipoIcms { get; set; }
        public Nullable<decimal> BaseIcms { get; set; }
        public Nullable<decimal> AliquotaIcms { get; set; }
        public Nullable<decimal> ValorIcms { get; set; }
        public string NomeProduto { get; set; }
        public string CodigoProduto { get; set; }
        public Nullable<decimal> BaseCalculoIpi { get; set; }
        public Nullable<decimal> AliquotaIpi { get; set; }
        public Nullable<decimal> ValorIpi { get; set; }
        public Nullable<decimal> Desconto { get; set; }
    
        public virtual NotaFiscal NotaFiscal { get; set; }
    }
}
