USE [Teste]
GO
IF OBJECT_ID('dbo.P_TOTAL_POR_CFOP') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.P_TOTALIZADOR_POR_CFOP
    IF OBJECT_ID('dbo.P_TOTAL_POR_CFOP') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE dbo.P_TOTAL_POR_CFOP >>>'
    ELSE
        PRINT '<<< PROCEDURE dbo.P_TOTAL_POR_CFOP APAGADA >>>'
END
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 
CREATE PROCEDURE dbo.P_TOTAL_POR_CFOP
AS
	SET NOCOUNT ON
		BEGIN
			SELECT 
				Cfop,
				SUM(BaseIcms) 'ValorTotalBaseIcms',
				SUM(ValorIcms) 'ValorTotalIcms',
				SUM(BaseCalculoIpi) 'ValorTotalBaseIpi',
				SUM(ValorIpi) 'ValorTotalIpi'
			FROM 
				NotaFiscalItem
			GROUP BY
				Cfop
		END	  
GO
GRANT EXECUTE ON dbo.P_TOTALIZADOR_POR_CFOP TO [public]
go
IF OBJECT_ID('dbo.P_TOTAL_POR_CFOP') IS NOT NULL
    PRINT '<<< PROCEDURE dbo.P_TOTAL_POR_CFOP CRIADA >>>'
ELSE
    PRINT '<<< FALHA NA CRIACAO DA PROCEDURE dbo.P_TOTAL_POR_CFOP >>>'
go


